apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-memorylimit
target:
  group: apps
  version: v1
  kind: Deployment
  name: app
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app
  spec:
    template:
      spec:
        containers:
        - name: app
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 100Mi


