apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## TODO Namespace
namespace: dev

resources:
- ../../base

# Patch Deployment
patchesStrategicMerge:
- patch-spring-profile.yaml
- patch-limits.yaml
- patch-replicas.yaml

# ConfigMap
configMapGenerator:
- files:
  - config-files/application.yaml
  name: env-config


