apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        # TODO
        - name: puername-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: development

