trigger:
  - /**

variables:
  GIT_VERSION_CONFIGURATION: './ci/GitVersion.yaml'
  JDK_VERSION: '1.11'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

  SEMVER_SHORTSHA_BUILDID: $(GitVersion.SemVer)_$(GitVersion.ShortSha)_$(Build.BuildID)
  NAME: $(Build.DefinitionName)

  SONAR_ORGANIZATION: 'keepcalm'
  SONAR_CLOUD: 'azure-c3smonkey'

  K8S_DEFAULT_IMAGE: 'c3smonkey/template:latest'
  K8S_DIR: 'k8s'
  DOCKER_REGISTRY: 'docker-registry.default.svc:5000'

jobs:
  # Semantic Version
  - job: SemVer
    displayName: "Semantic Version - Semantic Release"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: ci/templates/semver-steps.yaml

  # Maven Build Test and Sonar
  - job: Build
    dependsOn: SemVer
    displayName: "Build and Test Maven Artifact"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: ci/templates/sonar-prepare-steps.yaml
      - template: ci/templates/maven-build-steps.yaml
      - template: ci/templates/sonar-publish-steps.yaml

  # Maven Build Docker
  - job: BuildDockerImage
    dependsOn: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: ci/templates/maven-docker-build-steps.yaml

  # Maven Build Docker
  - job: BuildKustomize
    dependsOn: SemVer
    displayName: 'Kustomize Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: ci/templates/kustomize-build-steps.yaml

  # Tag Git Repo
  - job: TagGitRepo
    dependsOn: Build
    displayName: 'Create Tag on Git Repository'
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: ci/templates/git-tag-repository-steps.yaml

