trigger:
  - /**

pool:
  vmImage: 'ubuntu-latest'

variables:
  GIT_VERSION_CONFIGURATION: '../ci/GitVersion.yml'
  JDK_VERSION: '1.11'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

  SEMVER_SHORTSHA_BUILDID: $(GitVersion.SemVer)_$(GitVersion.ShortSha)_$(Build.BuildID)
  NAME: $(Build.DefinitionName)

  SONAR_ORGANIZATION: 'keepcalm'
  SONAR_CLOUD: 'azure-c3smonkey'

  K8S_DEFAULT_IMAGE: 'c3smonkey/template:latest'
  K8S_DIR: 'k8s'
  DOCKER_REGISTRY: 'docker-registry.default.svc:5000'

stages:
  # SemVer
  - stage: StageVersion
    displayName: 'Semantic Version'
    jobs:
      - job: SemVer
        displayName: "Semantic Version - Semantic Release"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: ci/templates/semver-steps.yaml

  # Kustomize
  - stage: StageKustomize
    displayName: 'Kustomize'
    jobs:
      - job: BuildKustomize
        displayName: 'Kustomize Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: ci/templates/kustomize-build-steps.yaml

  # Build
  - stage: StageBuild
    displayName: 'Build Artifact'
    dependsOn: StageVersion
    jobs:
      - job: Build
        displayName: "Build and Test Maven Artifact"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: ci/templates/maven-build-steps.yaml

  # Dockerize
  - stage: StageDockerBuild
    displayName: 'Build Docker Image'
    dependsOn: StageBuild
    jobs:
      - job: BuildDockerImage
        displayName: 'Build Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: ci/templates/maven-docker-build-steps.yaml

  # Tag only on master
  - stage: StageTag
    displayName: 'Create Tag on Git Repository'
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())
    dependsOn: StageDockerBuild
    jobs:
      - job: TagGitRepo
        displayName: 'Create Tag on Git Repository'
        condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: ci/templates/git-tag-repository-steps.yaml



