apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
  artifacts:
#    - image: harbor.c3smonkey.ch/c3smonkey/kboot-bname-service
    - image: registry.apps.c3smonkey.ch/dev/kboot-bname-service
      #      custom:
      #        buildCommand: ./mvnw spring-boot:build-image -D spring-boot.build-image.imageName=$IMAGE && docker push $IMAGE
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base-platform-api-0.3
        dependencies:
          paths:
            - pom.xml
            - src/main/resources
            - target/classes
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "target/classes/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: target/classes/
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
      - "k8s"
