apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: c3smonkey/template
        envFrom:
        - configMapRef:
            name: env-config
        ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
